#====================================================================
#       Macro & Assembler flags
#====================================================================

STADDR = 100000
MACFLAGS = -fb -g
ALNFLAGS = -v -v -e -g -l -rd -a $(STADDR) x 4000

# this one makes a mapfile
#ALNFLAGS = -v -v -e -g -l -m -rd -a $(STADDR) x 4000
# this one makes a bin file for Frog ;) (this is the whole ALN command though)
#ALNFLAGS = -rd -n -o mou.bin -a 4000 x x $(OBJ)

#====================================================================
#       Default Rules
#====================================================================
.SUFFIXES:      .o .s

.s.o:
	mac $(MACFLAGS) $*
 
#====================================================================
#       EXECUTABLES
#====================================================================

OBJ = mou_init.o mou_list.o mou_gpu.o gfx.o
 
mou.cof: $(OBJ)
#	aln $(ALNFLAGS) -o mou.cof $(OBJ) -i ..\\data\\jaguar.bin jagbits
	aln $(ALNFLAGS) -o mou.cof $(OBJ)

mou_init.o: mou_init.s mou.inc

mou_list.o: mou_list.s mou.inc

mou_gpu.o: mou_gpu.s mou.inc

kryspron.o: kryspron.s

